---
env:
  es6: true
  browser: true
  webextensions: true

parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true

globals:
  DOMPurify: readonly

extends: eslint:recommended

reportUnusedDisableDirectives: true

rules:
  no-await-in-loop: warn
  no-import-assign: error
  no-template-curly-in-string: error

  accessor-pairs:
    - warn
    - getWithoutSet: true
  array-callback-return: error
  class-methods-use-this: warn
  consistent-return: error

  curly:
    - error
    - multi-line
    - consistent
  default-case: error
  default-param-last: error
  dot-location:
    - error
    - object
  dot-notation: error # May clash with camelcase
  eqeqeq: error
  no-else-return:
    - error
    - allowElseIf: false
  no-implicit-coercion: error
  no-invalid-this: error
  no-loop-func: error
  no-multi-spaces:
    - warn
    - ignoreEOLComments: true
  no-new-func: error
  no-return-assign:
    - error
    - always
  no-return-await: error
  no-self-compare: error
  no-useless-concat: error
  no-useless-return: error
  no-sequences: error
  no-void: error
  require-await: error
  yoda: warn

  init-declarations:
    - error
    - always
  no-undef-init: error
  no-undefined: error
  no-use-before-define:
    - error
    - nofunc

  # Stylistic issues
  array-bracket-newline:
    - error
    - multiline: true
  array-element-newline:
    - error
    - consistent
  block-spacing: error
  brace-style: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  eol-last: error
  function-paren-newline:
    - warn
    - multiline
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - as-needed
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
    - SwitchCase: 1
      FunctionDeclaration:
        parameters: 2
      FunctionExpression:
        parameters: 2
      CallExpression:
        arguments: 2
      ArrayExpression: 1
      ObjectExpression: 1
      ImportDeclaration: first
  function-call-argument-newline:
    - error
    - consistent
  key-spacing: error
  keyword-spacing: error
  lines-between-class-members: error
  max-len:
    - error
    - code: 80
      ignoreRegExpLiterals: true
  new-cap: error
  new-parens: error
  no-bitwise: error
  no-multi-assign: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  no-negated-condition: error
  no-nested-ternary: error
  no-tabs: error
  no-trailing-spaces: error
  no-new-object: error
  no-array-constructor: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position:
    - error
    - beside
  object-curly-newline:
    - error
    - ImportDeclaration: never
      ObjectExpression:
        multiline: true
        # minProperties: 3
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  operator-linebreak:
    - error
    - after
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: function
    - blankLine: always
      prev: import
      next: let
    - blankLine: always
      prev: import
      next: const
  quote-props:
    - error
    - consistent-as-needed
    - keywords: true
  quotes:
    - error
    - single
  semi: error
  semi-spacing: error
  semi-style: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error

  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  generator-star-spacing:
    - error
    - after
  no-confusing-arrow: error
  no-duplicate-imports:
    - error
    - includeExports: true
  no-useless-computed-key:
    - error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  prefer-arrow-callback: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  template-curly-spacing: error
  yield-star-spacing:
    - error
    - after
  no-constant-condition:
    - error
    - checkLoops: false
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_$
  prefer-const: error
